### <span style="color: red"> Task 1:</span> Some errors are presented in the code below. Can you identify and corret them?

In [ ]:
import os
import csv

current_dir = os.getcwd()
filename = 'E1_T1.csv'    #can't find the file with current_directory + filename?
with open(filename, 'r', newline='') as f:
    csv_file = csv.reader(f)
    data = list(csv_file)
sentence=''
for word in data:
    sentence = sentence + ' '+ str(word) #need to convert the variable 'word' to str
print(sentence)
print(type(sentence))

### <span style="color: red"> Task 2:</span> Who has the most runner-up (i.e., second place) finishes in the histroy of NHL? Create a table with the teams and their runner-up finishes. The table must contain the the following columns:

-Team

-Total number of runner-up finishes

-Years [list of the years they finished as a runner-up]

You have to use Jupyter for the practice and produce a notebook with good readability.

### <span style="color: blue"> Solution:</span>

In [43]:
import pandas as pd
import numpy as np

file = 'Stanely_cup_winners_by_year.xlsx'
df = pd.read_excel(file)  #read the excel file into dataframe


i = 0
dict2 = {'Team':[],'Runner_up_finishes':[],'Years':[]} #Create a dictionary with keys(columns)

while i < len(df):
    team_w = df['Team'][i]
    team_r = df['Runner up'][i]
    year = df['Year'][i]   #in each row, read the values of dataframe
    
    if team_r not in dict2['Team']:
        dict2['Team'].append(team_r)   #put the team in dictionary
        dict2['Years'].append([year])   #put the Runner-up year in dictionary
        dict2['Runner_up_finishes'].append(1)   #the number of Runner-up is 1
    
    else:
        indx = dict2['Team'].index(team_r) 
        dict2['Years'][indx].append(year)   #put another Runner-up year in the dictionary
        dict2['Runner_up_finishes'][indx] += 1   #add 1 to the number of Runner-up
      
    i+=1 

df2 = pd.DataFrame(dict2)   #convert the dictionary to dataframe
df2 = df2.sort_values(by='Runner_up_finishes',ascending=False)   #sort the dataframe based on number of Runner-up finishes
df2 = df2.set_index(np.arange(0,len(df2)))

print(df2['Team'][0]+' has the most runner-up finishes in the history of NHL, with '+ str(df2['Runner_up_finishes'][0])+
      ' runner-up finishes in ' + str(df2['Years'][0]))

df2

Boston Bruins has the most runner-up finishes in the history of NHL, with 14 runner-up finishes in [2019, 2013, 1990, 1988, 1978, 1977, 1974, 1958, 1957, 1953, 1946, 1943, 1930, 1927]

,Team,Runner_up_finishes,Years
0,Boston Bruins,14,"[2019, 2013, 1990, 1988, 1978, 1977, 1974, 195..."
1,Detroit Red Wings,13,"[2009, 1995, 1966, 1964, 1963, 1961, 1956, 194..."
2,Montreal Canadiens,9,"[1989, 1967, 1955, 1954, 1952, 1951, 1947, 192..."
3,Toronto Maple Leafs,8,"[1960, 1959, 1940, 1939, 1938, 1936, 1935, 1933]"
4,New York Rangers,7,"[2014, 1979, 1972, 1950, 1937, 1932, 1929]"
5,Chicago Blackhawks,6,"[1992, 1973, 1971, 1965, 1962, 1944]"
6,Philadelphia Flyers,6,"[2010, 1997, 1987, 1985, 1980, 1976]"
7,St. Louis Blues,3,"[1970, 1969, 1968]"
8,Vancouver Canucks,3,"[2011, 1994, 1982]"
9,Vancouver Millionaires,3,"[1922, 1921, 1918]"
10,Calgary Flames,2,"[2004, 1986]"
11,Minnesota North Stars,2,"[1991, 1981]"
12,Victoria Cougars,2,"[1926, 1914]"
13,Buffalo Sabres,2,"[1999, 1975]"
14,Dallas Stars,2,"[2020, 2000]"
15,Ottawa Senators,2,"[2007, 1915]"
16,New Jersey Devils,2,"[2012, 2001]"
17,Edmonton Oilers,2,"[2006, 1983]"
18,Edmonton Eskimos,1,[1923]
19,Calgary Tigers,1,[1924]
20,Seattle Metropolitans,1,[1920]
21,Montreal Maroons,1,[1928]
22,Portland Rosebuds,1,[1916]
23,Sydney Miners,1,[1913]
24,Moncton Victories,1,[1912]
25,Chicago Black Hawks,1,[1931]
26,Florida Panthers,1,[1996]
27,New York Islanders,1,[1984]
28,Los Angeles Kings,1,[1993]
29,Washington Capitals,1,[1998]
30,Carolina Hurricanes,1,[2002]
31,Mighty Ducks of Anaheim,1,[2003]
32,Pittsburgh Penguins,1,[2008]
33,Tampa Bay Lightning,1,[2015]
34,San Jose Sharks,1,[2016]
35,Nashville Predators,1,[2017]
36,Vegas Golden Knights,1,[2018]
37,Port Arthur Bearcats,1,[1911]

### <span style="color: red"> Task 3:</span> With the help of matminer, 1. Retrive the 'steel_strength' dataset into a dataframe and clean your dataset (i.e., do some basic data exploration and analysis work on your data. For instance, check the statistics of the dataset, check for NaNs, drop duplicated data entries etc. It is alway the first thing to do before you start working on a dataset.) if needed; 2. Featurize the compositions of the materials; and 3. Perform correlation analysis and drop feature(s) with a coefficient greater than abs(0.8) from your dataframe.

### <span style="color: blue"> Solution:</span>

In [60]:
import matminer
import pandas
from matminer.datasets import load_dataset

df = load_dataset('steel_strength')   #load the dataset 'steel_strength'

df.describe()   #statistics check

from matminer.featurizers.conversions import StrToComposition
from tqdm.autonotebook import tqdm

df = StrToComposition().featurize_dataframe(df, "formula")   #Featurize the composition

blacklist = []

df2=df.select_dtypes(include=['float64'])  #Exclude the columns where the values are not float numbers
for column in df2:
    for column2 in df2:
        if column not in blacklist:   #When two columns have high correlations, avoid dropping both of them
            if abs(df2[column].corr(df2[column2])) > 0.8 and column != column2:
                df = df.drop([column2], axis=1)   #Drop the columns with correlation coefficient greater than abs(0.8)
                blacklist.append(column2)   #After a column has been dropped, avoid iterating it again
            
df

StrToComposition:   0%|          | 0/312 [00:00<?, ?it/s]

['cr', 'ni', 0.8107922113800446]
['yield strength', 'tensile strength', 0.821070612320314]

,formula,c,mn,si,cr,mo,v,n,nb,co,w,al,ti,yield strength,elongation,composition
0,Fe0.620C0.000953Mn0.000521Si0.00102Cr0.000110N...,0.02,0.05,0.05,0.01,2.95,0.01,0.00,0.01,15.00,0.00,0.15,1.55,2411.5,7.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al, Ti)"
1,Fe0.623C0.00854Mn0.000104Si0.000203Cr0.147Ni0....,0.18,0.01,0.01,13.44,3.01,0.46,0.04,0.01,19.46,2.35,0.04,0.00,1123.1,8.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, N, Nb, Co, W, Al)"
2,Fe0.625Mn0.000102Si0.000200Cr0.0936Ni0.129Mo0....,0.00,0.01,0.01,8.67,0.82,0.01,0.00,0.01,13.90,0.00,0.39,0.57,1736.3,NaN,"(Fe, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al, Ti)"
3,Fe0.634C0.000478Mn0.000523Si0.00102Cr0.000111N...,0.01,0.05,0.05,0.01,3.95,0.01,0.00,0.01,15.00,0.00,0.13,1.47,2487.3,9.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al, Ti)"
4,Fe0.636C0.000474Mn0.000518Si0.00101Cr0.000109N...,0.01,0.05,0.05,0.01,1.45,0.01,0.00,0.01,14.90,0.00,0.13,1.55,2249.6,8.5,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al, Ti)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,Fe0.823C0.0176Mn0.00183Si0.000198Cr0.0779Ni0.0...,0.38,0.18,0.01,7.27,3.77,0.96,0.00,0.01,4.90,0.00,0.03,0.00,1722.5,5.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al)"
308,Fe0.823Mn0.000618Si0.00101Cr0.0561Ni0.0984Mo0....,0.00,0.06,0.05,5.15,3.20,0.01,0.00,0.01,0.01,0.00,0.03,0.09,1019.0,19.0,"(Fe, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al, Ti)"
309,Fe0.825C0.0174Mn0.00175Si0.000201Cr0.0565Ni0.0...,0.37,0.17,0.01,5.20,5.84,1.05,0.00,0.91,4.88,0.00,0.03,0.00,1860.3,3.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al)"
310,Fe0.858C0.0191Mn0.00194Si0.000199Cr0.0753Ni0.0...,0.41,0.19,0.01,6.99,5.84,0.92,0.00,0.01,0.02,0.00,0.03,0.00,1812.1,2.0,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al)"
311,Fe0.860C0.0125Mn0.00274Si0.000198Cr0.00439Ni0....,0.27,0.27,0.01,0.41,0.49,0.07,0.00,0.01,3.90,0.00,0.03,0.00,1139.7,15.4,"(Fe, C, Mn, Si, Cr, Ni, Mo, V, Nb, Co, Al)"

### <span style="color: red"> Task 4:</span> Setup a private Github repository for this course. Name it MSE403_\<YourName>_\<YourStudentID>. You will be using this repo for homework submission and course project version control. A good place to get started is [here](https://docs.github.com/en/get-started/quickstart/hello-world). You can choose to use the GitHub via the terminal (<ins>recommanded</ins>), the [GitHub desktop app](https://desktop.github.com/), or the online GitHub platform. After setting up your repo, make sure to share your repo with [Jae]() and [Xiao](https://github.com/xshang93) by adding us as collabrators.